spring:
  application:
    name: heroesofddd
  docker:
    compose:
      enabled: true
axon:
  axonserver:
    context: default
    enabled: true
logging:
  level:
    org.axonframework.configuration: DEBUG